// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sharks.Data;

#nullable disable

namespace sharks.Migrations
{
    [DbContext(typeof(SharksDbContext))]
    [Migration("20251004130448_RemoveAdditionalTrackingFields")]
    partial class RemoveAdditionalTrackingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sharks.Models.Shark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SharkSpeciesId")
                        .HasColumnType("int");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TaggedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaggedLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SharkSpeciesId");

                    b.ToTable("Sharks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "Female",
                            Length = 3.2000000000000002,
                            Name = "Jaws",
                            Notes = "Tiburón tigre juvenil con comportamiento activo",
                            SharkSpeciesId = 2,
                            TagId = "TAG-100",
                            TaggedDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaggedLocation = "Australia, Port Lincoln",
                            Weight = 580.0
                        },
                        new
                        {
                            Id = 2,
                            Gender = "Male",
                            Length = 2.1000000000000001,
                            Name = "Lemon Drop",
                            Notes = "Tiburón limón joven en excelentes condiciones",
                            SharkSpeciesId = 3,
                            TagId = "TAG-200",
                            TaggedDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaggedLocation = "Bahamas, Bimini",
                            Weight = 75.0
                        },
                        new
                        {
                            Id = 3,
                            Gender = "Male",
                            Length = 4.7999999999999998,
                            Name = "Bruce",
                            Notes = "Tiburón blanco adulto con cicatrices distintivas en la aleta dorsal",
                            SharkSpeciesId = 1,
                            TagId = "TAG-001",
                            TaggedDate = new DateTime(2013, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaggedLocation = "Sudáfrica, False Bay",
                            Weight = 1150.0
                        });
                });

            modelBuilder.Entity("sharks.Models.SharkSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageLength")
                        .HasColumnType("float");

                    b.Property<double>("AverageWeight")
                        .HasColumnType("float");

                    b.Property<string>("ConservationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DangerLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SharkSpecies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageLength = 4.5,
                            AverageWeight = 1200.0,
                            ConservationStatus = "Vulnerable",
                            DangerLevel = "High",
                            Description = "El gran tiburón blanco es una especie de elasmobranquio lamniforme de la familia Lamnidae que se encuentra en las aguas costeras de todos los océanos.",
                            Habitat = "Aguas costeras templadas y subtropicales",
                            Name = "Gran Tiburón Blanco",
                            ScientificName = "Carcharodon carcharias"
                        },
                        new
                        {
                            Id = 2,
                            AverageLength = 3.5,
                            AverageWeight = 400.0,
                            ConservationStatus = "Near Threatened",
                            DangerLevel = "High",
                            Description = "El tiburón tigre es una especie de elasmobranquio carcarriniforme conocido por sus distintivas rayas oscuras.",
                            Habitat = "Aguas tropicales y subtropicales",
                            Name = "Tiburón Tigre",
                            ScientificName = "Galeocerdo cuvier"
                        },
                        new
                        {
                            Id = 3,
                            AverageLength = 2.5,
                            AverageWeight = 90.0,
                            ConservationStatus = "Vulnerable",
                            DangerLevel = "Medium",
                            Description = "El tiburón limón es una especie de tiburón requiem de color amarillento que habita en aguas poco profundas.",
                            Habitat = "Aguas costeras poco profundas tropicales",
                            Name = "Tiburón Limón",
                            ScientificName = "Negaprion brevirostris"
                        },
                        new
                        {
                            Id = 4,
                            AverageLength = 4.0,
                            AverageWeight = 230.0,
                            ConservationStatus = "Critically Endangered",
                            DangerLevel = "Medium",
                            Description = "El tiburón martillo gigante es la especie más grande de tiburón martillo, conocido por su cabeza distintiva en forma de martillo.",
                            Habitat = "Aguas costeras tropicales y subtropicales",
                            Name = "Tiburón Martillo",
                            ScientificName = "Sphyrna mokarran"
                        },
                        new
                        {
                            Id = 5,
                            AverageLength = 2.5,
                            AverageWeight = 130.0,
                            ConservationStatus = "Vulnerable",
                            DangerLevel = "High",
                            Description = "El tiburón toro es conocido por su capacidad de nadar en agua dulce y su naturaleza agresiva.",
                            Habitat = "Aguas costeras, ríos y lagos",
                            Name = "Tiburón Toro",
                            ScientificName = "Carcharhinus leucas"
                        });
                });

            modelBuilder.Entity("sharks.Models.SharkTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int>("SharkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrackingDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SharkId");

                    b.ToTable("SharkTrackings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = -34.60661m,
                            Longitude = 21.15244m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 7, 6, 4, 57, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Latitude = -34.78752m,
                            Longitude = 19.42479m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 6, 23, 2, 40, 9, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Latitude = -34.42487m,
                            Longitude = 21.09754m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 6, 15, 13, 15, 44, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Latitude = -34.70432272m,
                            Longitude = 20.21013441m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 6, 3, 2, 23, 57, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Latitude = -34.65556m,
                            Longitude = 19.37459m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 5, 28, 19, 53, 57, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Latitude = -34.63245m,
                            Longitude = 19.42612m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 4, 11, 0, 56, 6, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Latitude = -34.62952m,
                            Longitude = 19.42943m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 4, 10, 3, 4, 58, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Latitude = -34.62948m,
                            Longitude = 19.42926m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 4, 10, 1, 11, 30, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Latitude = -34.64901797m,
                            Longitude = 20.29276432m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 1, 16, 4, 30, 50, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Latitude = -34.66521297m,
                            Longitude = 20.26497576m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 1, 10, 13, 20, 14, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Latitude = -34.81799m,
                            Longitude = 20.23152m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2014, 1, 8, 1, 23, 54, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Latitude = -34.71725348m,
                            Longitude = 20.13079566m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 28, 0, 4, 59, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Latitude = -34.71818947m,
                            Longitude = 20.12474436m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 27, 14, 15, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Latitude = -34.72023786m,
                            Longitude = 20.11244288m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 26, 8, 43, 24, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Latitude = -34.72199931m,
                            Longitude = 20.11298288m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 26, 7, 55, 39, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Latitude = -34.73791136m,
                            Longitude = 20.0834699m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 25, 17, 1, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Latitude = -34.72689m,
                            Longitude = 20.09885m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 24, 22, 40, 11, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Latitude = -34.73446m,
                            Longitude = 20.08771m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 24, 16, 29, 27, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Latitude = -34.74514747m,
                            Longitude = 20.07850746m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 24, 12, 58, 21, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Latitude = -34.72674m,
                            Longitude = 20.10565m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 23, 15, 4, 22, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Latitude = -34.71498566m,
                            Longitude = 20.13827425m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 23, 15, 0, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Latitude = -34.72938875m,
                            Longitude = 20.10850444m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 23, 14, 31, 11, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Latitude = -34.74924733m,
                            Longitude = 20.07331304m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 23, 11, 31, 43, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Latitude = -34.76028641m,
                            Longitude = 20.06214768m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 22, 11, 34, 24, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Latitude = -34.7766m,
                            Longitude = 20.05964m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 22, 0, 56, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Latitude = -34.88268m,
                            Longitude = 20.28008m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 21, 11, 44, 7, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Latitude = -34.72235m,
                            Longitude = 20.35575m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 7, 21, 19, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Latitude = -34.65221m,
                            Longitude = 20.4527m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 3, 1, 22, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Latitude = -34.6388m,
                            Longitude = 20.49682m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 2, 18, 54, 48, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Latitude = -34.70552m,
                            Longitude = 20.44697m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 2, 6, 28, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Latitude = -34.73442m,
                            Longitude = 20.42501m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 2, 4, 46, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Latitude = -34.71613m,
                            Longitude = 20.43019m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 2, 1, 28, 30, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Latitude = -34.70838m,
                            Longitude = 20.42146m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 1, 20, 47, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Latitude = -34.64913m,
                            Longitude = 20.3989m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 12, 1, 3, 20, 58, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Latitude = -34.64329m,
                            Longitude = 20.40279m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 11, 30, 23, 42, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Latitude = -34.15962m,
                            Longitude = 22.12554m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 10, 9, 4, 43, 43, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Latitude = -34.15764m,
                            Longitude = 22.13796m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 10, 6, 8, 13, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Latitude = -34.17173m,
                            Longitude = 22.13131m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 10, 6, 8, 9, 4, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Latitude = -34.17378m,
                            Longitude = 22.13501m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 10, 5, 12, 59, 45, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Latitude = -34.51822475m,
                            Longitude = 20.64837612m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 10, 1, 12, 31, 22, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            Latitude = -34.47014m,
                            Longitude = 21.26723m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 30, 20, 0, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            Latitude = -34.54551m,
                            Longitude = 20.4386m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 29, 20, 12, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            Latitude = -34.54551m,
                            Longitude = 20.4386m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 29, 11, 12, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            Latitude = -34.63555m,
                            Longitude = 20.3954m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 23, 22, 11, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            Latitude = -34.6779m,
                            Longitude = 20.3477m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 21, 43, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            Latitude = -34.46257m,
                            Longitude = 20.48244m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 21, 34, 6, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            Latitude = -34.69846m,
                            Longitude = 20.30791m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 20, 59, 2, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            Latitude = -34.69825m,
                            Longitude = 20.31532m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 20, 28, 38, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            Latitude = -34.63555m,
                            Longitude = 20.3954m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 14, 22, 11, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            Latitude = -34.6779m,
                            Longitude = 20.3477m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 12, 43, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            Latitude = -34.69846m,
                            Longitude = 20.30791m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 11, 59, 2, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            Latitude = -34.69825m,
                            Longitude = 20.31532m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 28, 11, 28, 38, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            Latitude = -34.44422m,
                            Longitude = 21.16081m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 13, 16, 7, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            Latitude = -34.44657m,
                            Longitude = 21.17197m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 13, 15, 21, 36, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            Latitude = -34.49684m,
                            Longitude = 20.63756m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 4, 17, 47, 1, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            Latitude = -34.49818m,
                            Longitude = 20.64247m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 4, 16, 40, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            Latitude = -34.50088m,
                            Longitude = 20.66081m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 4, 15, 17, 1, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            Latitude = -34.52897m,
                            Longitude = 20.72558m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 4, 11, 55, 2, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            Latitude = -34.5428m,
                            Longitude = 20.75023m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 4, 11, 17, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            Latitude = -34.60189m,
                            Longitude = 20.68672m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 4, 11, 4, 34, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            Latitude = -34.65501m,
                            Longitude = 20.79118m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 4, 8, 41, 39, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            Latitude = -34.65861m,
                            Longitude = 20.7957m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 4, 8, 39, 50, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            Latitude = -34.32848m,
                            Longitude = 21.96493m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 2, 18, 32, 45, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            Latitude = -34.30852m,
                            Longitude = 21.98008m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 2, 17, 27, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            Latitude = -34.30231m,
                            Longitude = 21.98067m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 2, 13, 55, 48, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            Latitude = -34.12634m,
                            Longitude = 22.64236m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 1, 16, 38, 16, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            Latitude = -34.23273m,
                            Longitude = 22.45301m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 9, 1, 14, 12, 24, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            Latitude = -34.21839m,
                            Longitude = 22.4774m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 31, 18, 16, 24, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            Latitude = -34.22934m,
                            Longitude = 22.44067m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 31, 16, 50, 36, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            Latitude = -34.25628m,
                            Longitude = 22.45015m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 31, 16, 38, 35, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            Latitude = -34.27734m,
                            Longitude = 22.41724m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 31, 15, 59, 53, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            Latitude = -34.26512m,
                            Longitude = 22.39777m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 31, 15, 10, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            Latitude = -34.15828m,
                            Longitude = 22.24393m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 31, 11, 34, 12, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            Latitude = -34.13532m,
                            Longitude = 22.22857m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 31, 10, 47, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            Latitude = -34.13463m,
                            Longitude = 22.21766m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 31, 10, 23, 47, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            Latitude = -34.12228m,
                            Longitude = 22.31021m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 30, 16, 13, 2, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            Latitude = -34.1137m,
                            Longitude = 22.26619m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 30, 15, 21, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            Latitude = -34.10375m,
                            Longitude = 22.31803m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 29, 15, 36, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            Latitude = -34.52087m,
                            Longitude = 21.43964m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 26, 13, 30, 24, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            Latitude = -34.54522m,
                            Longitude = 21.39502m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 26, 12, 24, 43, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            Latitude = -34.47109m,
                            Longitude = 20.95329m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 26, 9, 46, 34, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            Latitude = -34.45055m,
                            Longitude = 20.93336m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 22, 21, 54, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            Latitude = -34.45245m,
                            Longitude = 20.94796m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 21, 20, 46, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            Latitude = -34.45403m,
                            Longitude = 20.94616m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 21, 5, 15, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            Latitude = -34.44983m,
                            Longitude = 21.1831m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 8, 53, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            Latitude = -34.46785m,
                            Longitude = 21.22962m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 7, 49, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            Latitude = -34.49348m,
                            Longitude = 21.2746m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 7, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            Latitude = -34.49699m,
                            Longitude = 21.28103m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 6, 32, 54, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            Latitude = -34.51975m,
                            Longitude = 21.29639m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 6, 6, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            Latitude = -34.52007m,
                            Longitude = 21.33642m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 5, 43, 37, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            Latitude = -34.50537m,
                            Longitude = 21.36702m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 4, 55, 26, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            Latitude = -34.48439m,
                            Longitude = 21.42315m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 4, 2, 58, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            Latitude = -34.47644m,
                            Longitude = 21.5909m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 2, 24, 41, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            Latitude = -34.43018m,
                            Longitude = 21.60368m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 25, 0, 26, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            Latitude = -34.24022m,
                            Longitude = 22.2462m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 16, 12, 33, 29, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            Latitude = -34.21432m,
                            Longitude = 22.25141m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 16, 11, 45, 21, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            Latitude = -34.21241m,
                            Longitude = 22.2579m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 16, 11, 44, 29, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            Latitude = -34.16615m,
                            Longitude = 22.24365m,
                            SharkId = 3,
                            TrackingDateTime = new DateTime(2013, 8, 16, 10, 57, 28, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("sharks.Models.Shark", b =>
                {
                    b.HasOne("sharks.Models.SharkSpecies", "Species")
                        .WithMany("Sharks")
                        .HasForeignKey("SharkSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("sharks.Models.SharkTracking", b =>
                {
                    b.HasOne("sharks.Models.Shark", "Shark")
                        .WithMany("TrackingData")
                        .HasForeignKey("SharkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shark");
                });

            modelBuilder.Entity("sharks.Models.Shark", b =>
                {
                    b.Navigation("TrackingData");
                });

            modelBuilder.Entity("sharks.Models.SharkSpecies", b =>
                {
                    b.Navigation("Sharks");
                });
#pragma warning restore 612, 618
        }
    }
}
